### ISSUE TITLE
Mawdor neegs signposts

### ISSUE THREAD

**Issue by TheSofox** [jpmorris33/ire#6]
In Mawdor, you are instructed to go to Northwest Peninsula, but only exit is south of town.
Might need signposts in the area, pointing towards the other villages (Lakeside, Peninsula, New (destroyed building), maybe lakes).
Maybe "torn down" signposts that were meant to point to airfields. Also put it in the two other maps for the other airfields too?

**Comment by jpmorris33** [comment]
No destroyed signs yet, but signs should be vastly improved as of d097b4e48e14898b1c02678312cc0f9d3ddd0420
